"""schema initial

Revision ID: 633586b28a0b
Revises: 
Create Date: 2026-09-08 01:42:37.015381+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '633586b28a0b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_families'))
    )
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_families_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_families_created_at'), ['created_at'], unique=False)

    op.create_table('grade_levels',
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('cycle', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('typical_age', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_levels')),
    sa.UniqueConstraint('country_code', 'code', name='uq_grade_country_code')
    )
    with op.batch_alter_table('grade_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_levels_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_grade_levels_created_at'), ['created_at'], unique=False)

    op.create_table('subjects',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects'))
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_subjects_created_at'), ['created_at'], unique=False)

    op.create_table('audit_events',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('actor_type', sa.String(length=24), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_audit_events_family_id_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_family_id'), ['family_id'], unique=False)
        batch_op.create_index('ix_audit_family_seq', ['family_id', 'seq'], unique=False)

    op.create_table('calendar_periods',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('period_type', sa.Enum('school', 'weekend', 'holiday', name='periodtype', native_enum=False, length=40), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_calendar_periods_family_id_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_periods'))
    )
    with op.batch_alter_table('calendar_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_periods_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_periods_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_periods_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_periods_start_date'), ['start_date'], unique=False)

    op.create_table('children',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('grade_code', sa.String(length=16), nullable=False),
    sa.Column('avatar', sa.String(length=64), nullable=False),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('xp_balance', sa.Integer(), nullable=False),
    sa.Column('xp_lifetime', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_activity_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_children_family_id_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_children'))
    )
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_children_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_children_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_children_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_children_grade_code'), ['grade_code'], unique=False)

    op.create_table('parents',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('owner', 'guardian', 'viewer', name='parentrole', native_enum=False, length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_prefs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_parents_family_id_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parents')),
    sa.UniqueConstraint('email', name='uq_parents_email')
    )
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_parents_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parents_firebase_uid'), ['firebase_uid'], unique=False)
        batch_op.create_index('ix_parents_phone', ['phone'], unique=False)

    op.create_table('topics',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('grade_code', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], name=op.f('fk_topics_parent_id_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_topics_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('country_code', 'grade_code', 'code', name='uq_topic_scope')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_grade_code'), ['grade_code'], unique=False)
        batch_op.create_index('ix_topics_lookup', ['country_code', 'grade_code', 'subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_subject_id'), ['subject_id'], unique=False)

    op.create_table('devices',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.Enum('android', 'ios', 'windows', 'macos', 'linux', 'web', name='deviceplatform', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'revoked', 'lost', name='devicestatus', native_enum=False, length=40), nullable=False),
    sa.Column('device_secret', sa.Text(), nullable=False),
    sa.Column('unlock_counter', sa.Integer(), nullable=False),
    sa.Column('accepted_counter', sa.Integer(), nullable=False),
    sa.Column('failed_code_attempts', sa.Integer(), nullable=False),
    sa.Column('code_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('hardware_id', sa.String(length=128), nullable=True),
    sa.Column('push_token', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('boot_id', sa.String(length=64), nullable=True),
    sa.Column('clock_skew_ms', sa.Integer(), nullable=False),
    sa.Column('tamper_score', sa.Float(), nullable=False),
    sa.Column('kiosk_enabled', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_devices_child_id_children'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_hardware_id'), ['hardware_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_status'), ['status'], unique=False)

    op.create_table('lockouts',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Enum('failed_assessment', 'too_many_attempts', 'daily_cap', 'curfew', 'parent_manual', 'tamper_detected', 'code_bruteforce', name='lockoutreason', native_enum=False, length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source_assessment_id', sa.Uuid(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by_parent_id', sa.Uuid(), nullable=True),
    sa.Column('review_topics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_lockouts_child_id_children'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lockouts'))
    )
    with op.batch_alter_table('lockouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lockouts_child_id'), ['child_id'], unique=False)
        batch_op.create_index('ix_lockouts_child_until', ['child_id', 'until'], unique=False)
        batch_op.create_index(batch_op.f('ix_lockouts_created_at'), ['created_at'], unique=False)

    op.create_table('mastery',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('subject_code', sa.String(length=32), nullable=False),
    sa.Column('ability', sa.Float(), nullable=False),
    sa.Column('ewma', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('band', sa.Enum('unknown', 'fragile', 'en_cours', 'acquis', 'expert', name='masteryband', native_enum=False, length=40), nullable=False),
    sa.Column('ease', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_mastery_child_id_children'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_mastery_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mastery')),
    sa.UniqueConstraint('child_id', 'topic_id', name='uq_mastery_child_topic')
    )
    with op.batch_alter_table('mastery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mastery_band'), ['band'], unique=False)
        batch_op.create_index(batch_op.f('ix_mastery_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mastery_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_mastery_review', ['child_id', 'next_review_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mastery_subject_code'), ['subject_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_mastery_topic_id'), ['topic_id'], unique=False)

    op.create_table('policy_profiles',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=True),
    sa.Column('period_type', sa.Enum('school', 'weekend', 'holiday', name='periodtype', native_enum=False, length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pass_score_pct', sa.Float(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty_bias', sa.Float(), nullable=False),
    sa.Column('reward_minutes', sa.Integer(), nullable=False),
    sa.Column('daily_cap_minutes', sa.Integer(), nullable=False),
    sa.Column('max_attempts_per_day', sa.Integer(), nullable=False),
    sa.Column('allow_parent_direct_unlock', sa.Boolean(), nullable=False),
    sa.Column('allow_assessment_unlock', sa.Boolean(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('cooldown_escalation', sa.Float(), nullable=False),
    sa.Column('review_required_before_retry', sa.Boolean(), nullable=False),
    sa.Column('minutes_per_100_xp', sa.Integer(), nullable=False),
    sa.Column('xp_daily_bonus_cap_minutes', sa.Integer(), nullable=False),
    sa.Column('practice_xp_multiplier', sa.Float(), nullable=False),
    sa.Column('curfew_start', sa.String(length=5), nullable=True),
    sa.Column('curfew_end', sa.String(length=5), nullable=True),
    sa.Column('subject_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extras', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_policy_profiles_child_id_children'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_policy_profiles_family_id_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_profiles')),
    sa.UniqueConstraint('family_id', 'child_id', 'period_type', name='uq_policy_scope')
    )
    with op.batch_alter_table('policy_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_profiles_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_profiles_family_id'), ['family_id'], unique=False)

    op.create_table('questions',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('type', sa.Enum('mcq_single', 'mcq_multi', 'true_false', 'numeric', 'short_text', 'fill_blank', 'ordering', 'matching', 'expression', 'handwritten', 'voice', name='questiontype', native_enum=False, length=40), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('difficulty_elo', sa.Float(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('choices', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('answer', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('hints', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('assets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('estimated_seconds', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('author_parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('times_served', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('avg_seconds', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_questions_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('external_ref', name='uq_questions_external_ref')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_author_parent_id'), ['author_parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_questions_selection', ['topic_id', 'difficulty', 'is_active'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], name=op.f('fk_refresh_tokens_parent_id_parents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_parent_id'), ['parent_id'], unique=False)

    op.create_table('xp_ledger',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('correct_answer', 'assessment_passed', 'perfect_score', 'streak_bonus', 'daily_goal', 'weakness_cleared', 'parent_grant', 'redeem', 'adjustment', name='xpreason', native_enum=False, length=40), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_xp_ledger_child_id_children'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_ledger'))
    )
    with op.batch_alter_table('xp_ledger', schema=None) as batch_op:
        batch_op.create_index('ix_xp_child_created', ['child_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_ledger_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_ledger_created_at'), ['created_at'], unique=False)

    op.create_table('assessments',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('unlock', 'practice', 'parent_assigned', 'placement', name='assessmentkind', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'submitted', 'graded', 'needs_review', 'expired', 'abandoned', name='assessmentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('policy_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('blueprint', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('pass_score_pct', sa.Float(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('points_max', sa.Float(), nullable=False),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.Column('score_pct', sa.Float(), nullable=True),
    sa.Column('score_out_of_20', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('reward_minutes', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('unlock_code_id', sa.Uuid(), nullable=True),
    sa.Column('lockout_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by_parent_id', sa.Uuid(), nullable=True),
    sa.Column('integrity', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_assessments_child_id_children'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_assessments_device_id_devices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_child_id'), ['child_id'], unique=False)
        batch_op.create_index('ix_assessments_child_status', ['child_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_status'), ['status'], unique=False)

    op.create_table('pairing_requests',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_parent_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('suggested_name', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_pairing_requests_child_id_children'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_parent_id'], ['parents.id'], name=op.f('fk_pairing_requests_created_by_parent_id_parents')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_pairing_requests_device_id_devices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pairing_requests'))
    )
    with op.batch_alter_table('pairing_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pairing_requests_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pairing_requests_code_hash'), ['code_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_pairing_requests_created_at'), ['created_at'], unique=False)

    op.create_table('screen_sessions',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('unlock_code_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.Enum('active', 'paused', 'ended', 'expired', 'revoked', name='screensessionstate', native_enum=False, length=40), nullable=False),
    sa.Column('granted_ms', sa.BigInteger(), nullable=False),
    sa.Column('bonus_ms', sa.BigInteger(), nullable=False),
    sa.Column('consumed_ms', sa.BigInteger(), nullable=False),
    sa.Column('offline_ms', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wall_deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_monotonic_ms', sa.BigInteger(), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=64), nullable=True),
    sa.Column('device_boot_id', sa.String(length=64), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('integrity_score', sa.Float(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_screen_sessions_child_id_children'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_screen_sessions_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screen_sessions'))
    )
    with op.batch_alter_table('screen_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screen_sessions_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_sessions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_sessions_state'), ['state'], unique=False)
        batch_op.create_index('ix_sessions_child_state', ['child_id', 'state', 'started_at'], unique=False)

    op.create_table('unlock_codes',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('issued', 'consumed', 'expired', 'revoked', name='unlockcodestatus', native_enum=False, length=40), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('issued_by_parent_id', sa.Uuid(), nullable=True),
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_offline', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_unlock_codes_child_id_children'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_unlock_codes_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unlock_codes'))
    )
    with op.batch_alter_table('unlock_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unlock_codes_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unlock_codes_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unlock_codes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_unlock_codes_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_unlock_codes_device_status', ['device_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_unlock_codes_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_unlock_codes_status'), ['status'], unique=False)

    op.create_table('assessment_items',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=True),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('subject_code', sa.String(length=32), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('mcq_single', 'mcq_multi', 'true_false', 'numeric', 'short_text', 'fill_blank', 'ordering', 'matching', 'expression', 'handwritten', 'voice', name='questiontype', native_enum=False, length=40), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('answer', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('answer_mode', sa.Enum('assisted', 'handwritten', 'voice', name='answermode', native_enum=False, length=40), nullable=True),
    sa.Column('strokes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('scratchpad', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('points_awarded', sa.Float(), nullable=False),
    sa.Column('points_max', sa.Float(), nullable=False),
    sa.Column('feedback', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('time_spent_ms', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('needs_manual_review', sa.Boolean(), nullable=False),
    sa.Column('manual_grade', sa.Float(), nullable=True),
    sa.Column('graded_by_parent_id', sa.Uuid(), nullable=True),
    sa.Column('parent_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_items_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_assessment_items_question_id_questions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_items'))
    )
    with op.batch_alter_table('assessment_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_items_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_items_subject_code'), ['subject_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_items_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index('ix_items_assessment_pos', ['assessment_id', 'position'], unique=False)

    op.create_table('screen_events',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('start', 'pause', 'resume', 'heartbeat', 'extend', 'end', 'expire', 'revoke', 'tamper', 'offline_gap', name='screeneventtype', native_enum=False, length=40), nullable=False),
    sa.Column('monotonic_ms', sa.BigInteger(), nullable=False),
    sa.Column('device_wall_ms', sa.BigInteger(), nullable=True),
    sa.Column('delta_ms', sa.BigInteger(), nullable=False),
    sa.Column('skew_ms', sa.BigInteger(), nullable=False),
    sa.Column('screen_on', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['screen_sessions.id'], name=op.f('fk_screen_events_session_id_screen_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screen_events'))
    )
    with op.batch_alter_table('screen_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screen_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_screen_events_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screen_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_screen_events_created_at'))

    op.drop_table('screen_events')
    with op.batch_alter_table('assessment_items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_assessment_pos')
        batch_op.drop_index(batch_op.f('ix_assessment_items_topic_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_items_subject_code'))
        batch_op.drop_index(batch_op.f('ix_assessment_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_assessment_items_assessment_id'))

    op.drop_table('assessment_items')
    with op.batch_alter_table('unlock_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unlock_codes_status'))
        batch_op.drop_index(batch_op.f('ix_unlock_codes_fingerprint'))
        batch_op.drop_index('ix_unlock_codes_device_status')
        batch_op.drop_index(batch_op.f('ix_unlock_codes_device_id'))
        batch_op.drop_index(batch_op.f('ix_unlock_codes_created_at'))
        batch_op.drop_index(batch_op.f('ix_unlock_codes_child_id'))
        batch_op.drop_index(batch_op.f('ix_unlock_codes_assessment_id'))

    op.drop_table('unlock_codes')
    with op.batch_alter_table('screen_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_child_state')
        batch_op.drop_index(batch_op.f('ix_screen_sessions_state'))
        batch_op.drop_index(batch_op.f('ix_screen_sessions_device_id'))
        batch_op.drop_index(batch_op.f('ix_screen_sessions_created_at'))
        batch_op.drop_index(batch_op.f('ix_screen_sessions_child_id'))

    op.drop_table('screen_sessions')
    with op.batch_alter_table('pairing_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pairing_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_pairing_requests_code_hash'))
        batch_op.drop_index(batch_op.f('ix_pairing_requests_child_id'))

    op.drop_table('pairing_requests')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_status'))
        batch_op.drop_index(batch_op.f('ix_assessments_created_at'))
        batch_op.drop_index('ix_assessments_child_status')
        batch_op.drop_index(batch_op.f('ix_assessments_child_id'))

    op.drop_table('assessments')
    with op.batch_alter_table('xp_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_ledger_created_at'))
        batch_op.drop_index(batch_op.f('ix_xp_ledger_child_id'))
        batch_op.drop_index('ix_xp_child_created')

    op.drop_table('xp_ledger')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_parent_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_created_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_selection')
        batch_op.drop_index(batch_op.f('ix_questions_created_at'))
        batch_op.drop_index(batch_op.f('ix_questions_author_parent_id'))

    op.drop_table('questions')
    with op.batch_alter_table('policy_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_profiles_family_id'))
        batch_op.drop_index(batch_op.f('ix_policy_profiles_created_at'))
        batch_op.drop_index(batch_op.f('ix_policy_profiles_child_id'))

    op.drop_table('policy_profiles')
    with op.batch_alter_table('mastery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mastery_topic_id'))
        batch_op.drop_index(batch_op.f('ix_mastery_subject_code'))
        batch_op.drop_index('ix_mastery_review')
        batch_op.drop_index(batch_op.f('ix_mastery_created_at'))
        batch_op.drop_index(batch_op.f('ix_mastery_child_id'))
        batch_op.drop_index(batch_op.f('ix_mastery_band'))

    op.drop_table('mastery')
    with op.batch_alter_table('lockouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lockouts_created_at'))
        batch_op.drop_index('ix_lockouts_child_until')
        batch_op.drop_index(batch_op.f('ix_lockouts_child_id'))

    op.drop_table('lockouts')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_status'))
        batch_op.drop_index(batch_op.f('ix_devices_hardware_id'))
        batch_op.drop_index(batch_op.f('ix_devices_created_at'))
        batch_op.drop_index(batch_op.f('ix_devices_child_id'))

    op.drop_table('devices')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_subject_id'))
        batch_op.drop_index('ix_topics_lookup')
        batch_op.drop_index(batch_op.f('ix_topics_grade_code'))
        batch_op.drop_index(batch_op.f('ix_topics_created_at'))
        batch_op.drop_index(batch_op.f('ix_topics_country_code'))

    op.drop_table('topics')
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index('ix_parents_phone')
        batch_op.drop_index(batch_op.f('ix_parents_firebase_uid'))
        batch_op.drop_index(batch_op.f('ix_parents_family_id'))
        batch_op.drop_index(batch_op.f('ix_parents_created_at'))

    op.drop_table('parents')
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_children_grade_code'))
        batch_op.drop_index(batch_op.f('ix_children_family_id'))
        batch_op.drop_index(batch_op.f('ix_children_created_at'))
        batch_op.drop_index(batch_op.f('ix_children_country_code'))

    op.drop_table('children')
    with op.batch_alter_table('calendar_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_periods_start_date'))
        batch_op.drop_index(batch_op.f('ix_calendar_periods_family_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_periods_end_date'))
        batch_op.drop_index(batch_op.f('ix_calendar_periods_created_at'))

    op.drop_table('calendar_periods')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_family_seq')
        batch_op.drop_index(batch_op.f('ix_audit_events_family_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_created_at'))
        batch_op.drop_index(batch_op.f('ix_subjects_code'))

    op.drop_table('subjects')
    with op.batch_alter_table('grade_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_levels_created_at'))
        batch_op.drop_index(batch_op.f('ix_grade_levels_country_code'))

    op.drop_table('grade_levels')
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_families_created_at'))
        batch_op.drop_index(batch_op.f('ix_families_country_code'))

    op.drop_table('families')
    # ### end Alembic commands ###
